/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as privateRouteRouteImport } from './app/(private)/route'
import { Route as publicIndexRouteImport } from './app/(public)/index'
import { Route as publicSignUpRouteImport } from './app/(public)/sign-up'
import { Route as publicSignInRouteImport } from './app/(public)/sign-in'
import { Route as publicAboutRouteImport } from './app/(public)/about'
import { Route as privateHomeRouteImport } from './app/(private)/home'
import { Route as privateCommunityCommunityIdChatRouteImport } from './app/(private)/community/$communityId/chat'

const privateRouteRoute = privateRouteRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSignUpRoute = publicSignUpRouteImport.update({
  id: '/(public)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSignInRoute = publicSignInRouteImport.update({
  id: '/(public)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAboutRoute = publicAboutRouteImport.update({
  id: '/(public)/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const privateHomeRoute = privateHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateCommunityCommunityIdChatRoute =
  privateCommunityCommunityIdChatRouteImport.update({
    id: '/community/$communityId/chat',
    path: '/community/$communityId/chat',
    getParentRoute: () => privateRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/home': typeof privateHomeRoute
  '/about': typeof publicAboutRoute
  '/sign-in': typeof publicSignInRoute
  '/sign-up': typeof publicSignUpRoute
  '/': typeof publicIndexRoute
  '/community/$communityId/chat': typeof privateCommunityCommunityIdChatRoute
}
export interface FileRoutesByTo {
  '/home': typeof privateHomeRoute
  '/about': typeof publicAboutRoute
  '/sign-in': typeof publicSignInRoute
  '/sign-up': typeof publicSignUpRoute
  '/': typeof publicIndexRoute
  '/community/$communityId/chat': typeof privateCommunityCommunityIdChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(private)': typeof privateRouteRouteWithChildren
  '/(private)/home': typeof privateHomeRoute
  '/(public)/about': typeof publicAboutRoute
  '/(public)/sign-in': typeof publicSignInRoute
  '/(public)/sign-up': typeof publicSignUpRoute
  '/(public)/': typeof publicIndexRoute
  '/(private)/community/$communityId/chat': typeof privateCommunityCommunityIdChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/home'
    | '/about'
    | '/sign-in'
    | '/sign-up'
    | '/'
    | '/community/$communityId/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/home'
    | '/about'
    | '/sign-in'
    | '/sign-up'
    | '/'
    | '/community/$communityId/chat'
  id:
    | '__root__'
    | '/(private)'
    | '/(private)/home'
    | '/(public)/about'
    | '/(public)/sign-in'
    | '/(public)/sign-up'
    | '/(public)/'
    | '/(private)/community/$communityId/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  privateRouteRoute: typeof privateRouteRouteWithChildren
  publicAboutRoute: typeof publicAboutRoute
  publicSignInRoute: typeof publicSignInRoute
  publicSignUpRoute: typeof publicSignUpRoute
  publicIndexRoute: typeof publicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/sign-up': {
      id: '/(public)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof publicSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/sign-in': {
      id: '/(public)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof publicSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/about': {
      id: '/(public)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof publicAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/home': {
      id: '/(private)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof privateHomeRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/community/$communityId/chat': {
      id: '/(private)/community/$communityId/chat'
      path: '/community/$communityId/chat'
      fullPath: '/community/$communityId/chat'
      preLoaderRoute: typeof privateCommunityCommunityIdChatRouteImport
      parentRoute: typeof privateRouteRoute
    }
  }
}

interface privateRouteRouteChildren {
  privateHomeRoute: typeof privateHomeRoute
  privateCommunityCommunityIdChatRoute: typeof privateCommunityCommunityIdChatRoute
}

const privateRouteRouteChildren: privateRouteRouteChildren = {
  privateHomeRoute: privateHomeRoute,
  privateCommunityCommunityIdChatRoute: privateCommunityCommunityIdChatRoute,
}

const privateRouteRouteWithChildren = privateRouteRoute._addFileChildren(
  privateRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  privateRouteRoute: privateRouteRouteWithChildren,
  publicAboutRoute: publicAboutRoute,
  publicSignInRoute: publicSignInRoute,
  publicSignUpRoute: publicSignUpRoute,
  publicIndexRoute: publicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
